### ISSUE TITLE
pip install -e git+gitlab:tensorflow/sphericalHarmonicsFlow#egg=SphericalHarmonicsFlow ERROR

### ISSUE THREAD

**Issue by ysfAskri** [da-h/sphericalHarmonicsFlow#2]
`pip install -e git+gitlab:tensorflow/sphericalHarmonicsFlow#egg=SphericalHarmonicsFlow
`
Obtaining SphericalHarmonicsFlow from git+gitlab:tensorflow/sphericalHarmonicsFlow#egg=SphericalHarmonicsFlow
  Cloning gitlab:tensorflow/sphericalHarmonicsFlow to /home/youssef/tensorflow/venv/src/sphericalharmonicsflow
ssh: Could not resolve hostname gitlab: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Command "git clone -q gitlab:tensorflow/sphericalHarmonicsFlow /home/youssef/tensorflow/venv/src/sphericalharmonicsflow" failed with error code 128 in None

When I make directory : 

 `mkdir /home/youssef/tensorflow/venv/src/sphericalharmonicsflow`
` pip install -e git+gitlab:tensorflow/sphericalHarmonicsFlow#egg=SphericalHarmonicsFlow
`
Obtaining SphericalHarmonicsFlow from git+gitlab:tensorflow/sphericalHarmonicsFlow#egg=SphericalHarmonicsFlow
  Directory /home/youssef/tensorflow/venv/src/sphericalharmonicsflow already exists, and is not a git clone.
  The plan is to install the git repository gitlab:tensorflow/sphericalHarmonicsFlow
What to do?  (i)gnore, (w)ipe, (b)ackup 

==> (I) ,  (w) & (b)  gives same error msg

**Comment by da-h** [comment]
Hi *ysfAskri*,

thanks for your request.

I fixed the installation link now.
**Please use**
```
pip install -e git+https://github.com/da-h/sphericalHarmonicsFlow#egg=SphericalHarmonicsFlow
```
instead.

Best,
*da-h*
